export const Project_skill_data = [
  {
    skill_name: "Html 5",
    Image: "/html.png",
    width: 45,
    height: 45,
  },
  {
    skill_name: "Css",
    Image: "/css.png",
    width: 45,
    height: 45,
  },
  {
    skill_name: "Java Script",
    Image: "/js.png",
    width: 45,
    height: 45,
  },
  {
    skill_name: "Tailwind Css",
    Image: "/tailwind.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "React",
    Image: "/react.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Angular",
    Image: "/angularjs.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Redux",
    Image: "/redux.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "ASP .Net",
    Image: "/asp.net.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Type Script",
    Image: "/ts.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Next js 13",
    Image: "/next.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Mongo db",
    Image: "/mongodb.png",
    width: 40,
    height: 40,
  },

  {
    skill_name: "Node js",
    Image: "/node-js.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Unreal Engine 5",
    Image: "/UnrealEngine5.png",
    width: 40,
    height: 40,
  },
  {
    skill_name: "Python",
    Image: "/python.png",
    width: 45,
    height: 45,
  },
  {
    skill_name: "Mongo db",
    Image: "/mongodb.png",
    width: 20,
    height: 25,
  },
  {
    skill_name: "C",
    Image: "/cpp.png",
    width: 45,
    height: 45,
  },
  {
    skill_name: "Steam",
    Image: "/steam.png",
    width: 40,
    height: 40,
  },
  {
    skill_name: "jQuery",
    Image: "/jQUery.png",
    width: 45,
    height: 45,
  },
  {
    skill_name: "PHP",
    Image: "/php.png",
    width: 45,
    height: 45,
  },
  {
    skill_name: "SQL",
    Image: "/sql.png",
    width: 45,
    height: 45,
  },
  {
    skill_name: "AnSYS",
    Image: "/ansys.png",
    width: 80,
    height: 50,
  },
  {
    skill_name: "Matlab",
    Image: "/Matlab.png",
    width: 40,
    height: 40,
  },
  {
    skill_name: "C",
    Image: "/Clang.png",
    width: 45,
    height: 45,
  },
];
